### ISSUE TITLE
Question about using data descriptors for class attributes.

### ISSUE THREAD

**Issue by lots0logs** [sad2project/descriptor-tools#1]
Hi, I'm trying to determine if your library could help me achieve the end result I want. (Sorry for using github issue to ask a question :sweat_smile: ) I have some custom classes that allow attribute access to data stored in redis. I originally wrote the code almost a year ago and it works well. Though I would like to use data descriptors instead of overriding `__getattribute__` and `__setattr__` like I am doing currently. 

The issue I am running into is that the descriptor protocol only works when assigned at the class level and some of the classes have many attributes--so many that I dont want to define them all separately. I am looking for a way to do it by looping through a dict which contains lists of attribute names grouped by value type. I have been searching online for a while but cant find any examples that fit my use-case. Could your library help me in some way? Any advice you could offer will be greatly appreciated. Of course I'd understand if you decide this is outside the scope of what github issues are for (because obviously it is)

Cheers!

**Comment by sad2project** [comment]
Yes, this is not the best use for issues, but it works fine.

From the little bit I can tell, this library won't be much help with that specific issue, but it can help with writing the descriptors in the first place.

Now, I certainly don't mind trying to help you figure this problem out. Could you give me an example of what you'd like the use of that dict to look like? I'm not sure I understand what you're asking for.

Also, please answer this by emailing me: sad2project@gmail.com .

**Comment by Vgr255** [comment]
(I know this is closed, but still)

Sounds like a base class with your prefered descriptors would be a good idea. Then you merely have to subclass it to get the descriptors for free! Although I'm not sure if it'd work in your case, it's worth a shot.

(You can also CC your emails to me as well if you want: vgr255@live.ca )

**Comment by lots0logs** [comment]
@sad2project @Vgr255  Thanks for your quick responses and offers to take a look at what I had. I really appreciate it! Though I actually was able to figure it out (finally!). It appears to be working exactly how I want. If you or anyone else who happens to stumble upon this issue would like to check out the solution I came up with, you can find it here:

https://github.com/antergos/antbs/blob/e8f2ce0190e0abbf63751396f8eaa2b2d56b3b1e/antbs/database/base_objects/redis_hash.py

Thanks again! BTW @sad2project I think this library is going to be very useful to many. There really isnt anything like it available (that I could find at least) :+1:

**Comment by sad2project** [comment]
I'm glad to hear it! 
Thanks for what you said about the library, too! I was really surprised about how little I could find on descriptors out there, which is why I wrote my book (http://www.lulu.com/spotlight/jacobz_20) which led to me writing this library.
